
export const SET_USER = "SET_USER";
export const SET_ERROR = "SET_ERROR";
export const SET_TRANSACTION = "SET_TRANSACTION"
export const LOAD_TRANSACTION = "LOAD_TRANSACTION"
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION"
export const DELETE_TRANSACTION = "DELETE_TRANSACTION"
export const SET_WORKS = "SET_WORKS";
export const SET_LOANS = "SET_LOANS";
export const SET_MESSAGE = "SET_MESSAGE";
export const UPDATE_USER = "UPDATE_USER";
export const LOAD_LOANS = "LOAD_LOANS"
export const LOAD_ALL_LOANS = "LOAD_ALL_LOANS"
export const DELETE_LOANS = "DELETE_LOANS"
export const LOAD_USERS = "LOAD_USERS"
export const DELETE_USER = "DELETE_USER"